name: Build GKI

on:
  workflow_dispatch:
   inputs:
    LTO:
     description: 'LTO Type'
     required: true
     default: ''
     type: choice
     options:
     - 'full'
     - 'thin'
     - 'none'

    KSU:
     description: 'KSU'
     required: false
     default: false
     type: boolean

    KSUNEXT:
     description: 'KSU-Next (WIP)'
     required: false
     default: true
     type: boolean

    SUSFS4KSU:
     description: 'SUSFS4KSU'
     required: false
     default: true
     type: boolean

    NOTE:
     description: 'Release Note'
     required: false

jobs:
  build:
    name: Build GKI Kernel
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Free up storage
      uses: rokibhasansagar/slimhub_actions@main

    - name: Build
      run: |
       [ -x "build.sh" ] || chmod a+x build.sh
       [ -x "telegram_functions.sh" ] || chmod a+x telegram_functions.sh

       export LTO_TYPE="${{ inputs.LTO }}"

       if [ "${{ inputs.SUSFS4KSU }}" == "true" ]; then
            export USE_KSU_SUSFS="yes"
       fi

       if [ "${{ inputs.KSU }}" == "true" ]; then
            export USE_KSU="yes"
       fi

       if [ "${{ inputs.KSUNEXT }}" == "true" ]; then
            export USE_KSU_NEXT="yes"
       fi

       if [ -n "${{ inputs.NOTE }}" ]; then
            export NOTE="${{ inputs.NOTE }}"
       fi

       export chat_id="${{ secrets.CHAT_ID }}"
       export token="${{ secrets.TOKEN }}"
       ./build.sh
