name: Build GKI

on:
  workflow_dispatch:
   inputs:
    LTO:
     description: 'LTO Type'
     required: true
     default: ''
     type: choice
     options:
     - 'full'
     - 'thin'
     - 'none'
    SUSFS4KSU:
     description: 'Do you want to include SUSFS4KSU?'
     required: true
     default: ''
     type: choice
     options:
     - 'Yes'
     - 'No'
     
jobs:
  build:
    name: Build GKI Kernel 
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 16
        
    - name: Free up storage
      uses: rokibhasansagar/slimhub_actions@main

    - name: Build
      run: |
       [ -x "build.sh" ] || chmod a+x build.sh
       [ -x "telegram_functions.sh" ] || chmod a+x telegram_functions.sh
       export LTO_TYPE="${{ inputs.LTO }}"
       export chat_id="${{ secrets.CHAT_ID }}"
       export token="${{ secrets.TOKEN }}"
       ./build.sh
